import uuid
from datetime import datetime
from typing import List, Optional

from pgvector.sqlalchemy import Vector
from sqlalchemy import DateTime, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.types import UserDefinedType

from app.database import Base


class TSVector(UserDefinedType):
    """PostgreSQL tsvector type for SQLAlchemy."""
    cache_ok = True

    def get_col_spec(self) -> str:
        return "TSVECTOR"


class MemoryEntry(Base):
    __tablename__ = "memory_entries"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # Entry types: narrative_fact, commit_summary, release_note, user_annotation, faq_answer
    entry_type: Mapped[str] = mapped_column(String(100), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    # Source reference — e.g. commit SHA, release tag, or "manual"
    source_ref: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    # 768-dimensional embedding (nomic-embed-text / Gemini text-embedding-004)
    embedding: Mapped[Optional[List[float]]] = mapped_column(Vector(768), nullable=True)
    # Full-text search vector (auto-updated by DB trigger)
    search_vector = mapped_column(TSVector(), nullable=True)
    # Context description for contextual retrieval (generated by AI on write)
    context_description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    project: Mapped["Project"] = relationship(  # noqa: F821
        "Project", back_populates="memory_entries"
    )
